// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoz9Z9W6EtHI6XNkjFUKCvne-GdU1IB_o',
    appId: '1:345864991845:web:5338488aa0c89261af028c',
    messagingSenderId: '345864991845',
    projectId: 'sample-flutter-study',
    authDomain: 'sample-flutter-study.firebaseapp.com',
    storageBucket: 'sample-flutter-study.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeh-0u9WqUoEJVKQCpQ2HVNoK-9NTopME',
    appId: '1:345864991845:android:d2ed9c964249a483af028c',
    messagingSenderId: '345864991845',
    projectId: 'sample-flutter-study',
    storageBucket: 'sample-flutter-study.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxnIuSyE4f6s8WcX6McntqBXleL1pEi5k',
    appId: '1:345864991845:ios:3156c4dcd8204051af028c',
    messagingSenderId: '345864991845',
    projectId: 'sample-flutter-study',
    storageBucket: 'sample-flutter-study.appspot.com',
    iosClientId: '345864991845-vbpa5e6emr6hfvshhji1ko4tkghf825f.apps.googleusercontent.com',
    iosBundleId: 'com.example.fastAppBase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxnIuSyE4f6s8WcX6McntqBXleL1pEi5k',
    appId: '1:345864991845:ios:3156c4dcd8204051af028c',
    messagingSenderId: '345864991845',
    projectId: 'sample-flutter-study',
    storageBucket: 'sample-flutter-study.appspot.com',
    iosClientId: '345864991845-vbpa5e6emr6hfvshhji1ko4tkghf825f.apps.googleusercontent.com',
    iosBundleId: 'com.example.fastAppBase',
  );
}
